### ISSUE TITLE
Add list of keyframes to the animation widget

### ISSUE THREAD

**Issue by sofroniewn** [sofroniewn/napari-animation#12]
Next step for the animation widget would be to add a list of keyframes (one day with little thumbnails) to aid in the movie making.

<img width="1200" alt="Screen Shot 2021-01-11 at 9 11 07 AM" src="https://user-images.githubusercontent.com/6531703/104216527-07517480-53ef-11eb-8b11-e08276854e09.png">

This could appear below the `Capture Frame` button. We a could use [QListWidget](https://doc.qt.io/qt-5/qlistwidget.html) or [QListView](https://doc.qt.io/qt-5/qlistview.html)  and custom [QListItemWidget](https://doc.qt.io/qt-5/qlistwidgetitem.html). I would not copy the implementation of the Qt side of the layer list in napari which defined our own QScrollArea.

Reordering the items in the list in the GUI should reorder the keyframes for when the movie gets made. Adding/ deleting keyframes should add/ delete items in the GUI.

The "selected" item in the list should then correspond to the "current" keyframe, and we could add a `Delete Frame` button too.

It might also be nice if you could adjust things like the easing/ number of steps of the "selected/ current" frame using the buttons at the top, though we'd need to think about how to do that and make it so that you can add a new key frame nicely too. I wouldn't worry about that at first, but just mentioning it as something we might want.

@alisterburt if you were interested in working on I can help. Probably first step would be for you to make a new PR trying out one of the list approaches. Some of the bidirectional syncing might get tricky, as might the thumbnail stuff, so it's fine to start with something simple and then improve. @tlambert03 might also have good ideas on the List stuff if you run into trouble too!!

**Comment by alisterburt** [comment]
@sofroniewn definitely interested! I'll stick up a work in progress PR asap to get the ball rolling, looking forward to delving into the UI side of things a bit more.

**Comment by alisterburt** [comment]
closed by #14
